// Package telemetrystream provides infrastructure for TCP-based communication
// between the mothership server and rover clients, including telemetry streaming.
package telemetrystream

import (
	"encoding/json"
	"fmt"
	"log"
	"net"
	"time"

	"space-mission/pkg/models"
)

// TelemetryClient sends telemetry data from a rover to a TelemetryServer over TCP.
// It maintains connection state, serialization, and handles periodic sending in a safe,
// concurrent manner.
type TelemetryClient struct {
	serverAddress string        // TCP address (IP:port) of the TelemetryServer (mothership)
	conn          *net.TCPConn  // Established TCP connection to the server
	connected     bool          // Indicates if the client is currently connected to the server
	streaming     bool          // Indicates if the client is currently streaming to the server
	encoder       *json.Encoder // Encoder for serializing telemetry data to JSON over the connection
	sendInterval  time.Duration // How often telemetry data should be sent (e.g. every 2 seconds)
	stopChan      chan struct{} // Channel to signal background goroutine to stop sending and disconnect
}

// NewTelemetryClient creates a new TelemetryClient instance with the specified server
// address and telemetry send interval. The stop channel is initialized internally.
func NewTelemetryClient(serverAddress string, sendInterval time.Duration) *TelemetryClient {
	if sendInterval == 0 {
		sendInterval = time.Second // default to 1 second interval
	}
	return &TelemetryClient{
		serverAddress: serverAddress,
		sendInterval:  sendInterval,
		stopChan:      make(chan struct{}),
	}
}

// Connect establishes a TCP connection to the telemetry server and prepares the JSON encoder.
func (c *TelemetryClient) Connect() error {

	if c.connected {
		return nil // Already connected
	}

	conn, err := net.Dial("tcp", c.serverAddress)
	if err != nil {
		return fmt.Errorf("failed to connect to telemetry server: %w", err)
	}

	c.conn = conn.(*net.TCPConn)
	c.encoder = json.NewEncoder(conn)
	c.connected = true

	log.Printf("TelemetryClient connected to %s", c.serverAddress)
	return nil
}

// Send transmits a single telemetry data packet to the server. The RoverID and Timestamp fields
// are set automatically before sending.
func (c *TelemetryClient) Send(telemetry *models.TelemetryData) error {

	if !c.connected {
		return fmt.Errorf("client is not connected")
	}

	// Set write deadline to avoid blocking indefinitely
	c.conn.SetWriteDeadline(time.Now().Add(5 * time.Second))

	if err := c.encoder.Encode(telemetry); err != nil {
		c.conn.Close()
		c.connected = false
		return fmt.Errorf("failed to send telemetry data: %w", err)
	}

	return nil
}

// StartStreaming begins periodically sending telemetry data generated by the provided dataSource
// function. It launches a background goroutine which can be stopped by calling Stop().
func (c *TelemetryClient) StartStreaming(dataSource func() *models.TelemetryData) error {
	if !c.connected {
		if err := c.Connect(); err != nil {
			return err
		}
	}

	if c.streaming {
		return fmt.Errorf("client is already streaming")
	}

	go c.streamLoop(dataSource)
	c.streaming = true

	log.Printf("Started telemetry streaming every %s", c.sendInterval)
	return nil
}

// streamLoop continuously sends telemetry data at intervals until stopped.
func (c *TelemetryClient) streamLoop(dataSource func() *models.TelemetryData) {
	ticker := time.NewTicker(c.sendInterval)
	defer ticker.Stop()

	for {
		select {
		case <-c.stopChan:
			return
		case <-ticker.C:
			telemetry := dataSource()
			if telemetry == nil {
				log.Printf("Telemetry source returned nil")
				continue
			}
			if err := c.Send(telemetry); err != nil {
				log.Printf("Error sending telemetry: %v", err)
				return
			}
		}
	}
}

// IsConnected returns whether the TelemetryClient currently has an active connection.
func (c *TelemetryClient) IsConnected() bool {
	return c.connected
}

// Stop stops the background telemetry streaming and closes the TCP connection gracefully.
func (c *TelemetryClient) Stop() error {
	close(c.stopChan)

	if c.conn != nil {
		if err := c.conn.Close(); err != nil {
			return fmt.Errorf("error closing connection: %w", err)
		}
		c.conn = nil
	}
	c.connected = false

	log.Printf("TelemetryClient stopped")
	return nil
}
